"""add student fee schedule fields

Revision ID: aa9631f94d09
Revises: 9f158b88aeb1
Create Date: 2026-07-05 17:46:54.424273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9631f94d09'
down_revision: Union[str, Sequence[str], None] = '9f158b88aeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('daily_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column(
        'students',
        sa.Column('scheduled_days', sa.JSON(), nullable=False, server_default='[]'),
    )
    op.add_column('students', sa.Column('monthly_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'monthly_fee')
    op.drop_column('students', 'scheduled_days')
    op.drop_column('students', 'daily_fee')
    # ### end Alembic commands ###
