"""add fee structure billing period fields

Revision ID: df3f22a7f6f6
Revises: aa9631f94d09
Create Date: 2026-07-05 18:33:21.087408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3f22a7f6f6'
down_revision: Union[str, Sequence[str], None] = 'aa9631f94d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_structures', sa.Column('billing_year', sa.Integer(), nullable=True))
    op.add_column('fee_structures', sa.Column('billing_month', sa.Integer(), nullable=True))
    op.add_column(
        'fee_structures',
        sa.Column('is_auto_generated', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_structures', 'is_auto_generated')
    op.drop_column('fee_structures', 'billing_month')
    op.drop_column('fee_structures', 'billing_year')
    # ### end Alembic commands ###
